---
abstract: 'Generate your dist/dist parts from custom global templates.'
author:
  - 'Kent Fredric <kentnl at cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-App-Command-generate
provides:
  Dist::Zilla::App::Command::generate:
    file: lib/Dist/Zilla/App/Command/generate.pm
    version: 0.01000001
  Dist::Zilla::Role::Generator:
    file: lib/Dist/Zilla/Role/Generator.pm
    version: 0.01000001
  Dist::Zilla::Types::Generator:
    file: lib/Dist/Zilla/Types/Generator.pm
    version: 0.01000001
requires:
  Test::More: 0
resources:
  repository: http://github.com/kentfredric/Dist-Zilla-App-Command-generate/tree
version: 0.01000001
